<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Zizaco\Entrust\Traits\EntrustUserTrait;
use Log;

class PublicF extends Model
{
    public $table = "publics";
    protected $fillable=[
        'Public_ID',
        'Finance_ID',
        'TtlCurntAsst',
        'Dep_CapAsst_NetDep',
        'OtherNoncurntAsst',
        'TtlNoncurntAsst',
        'LTermDebt_CrtPrt',
        'OtherCurntLiab',
        'TtlCurntLiab',
        'LtermDebt',
        'OtherNoncurntLiab',
        'TtlNoncurntLiab',
        'InvCapAsst_NetRelDebt',
        'Restr_Expnd',
        'Lcl',
        'UnRestr',
        'LImpt_EndBal',
        'Inf_EndBal',
        'Blds_EndBal',
        'Equ_IncArt_LibCol_EndBal',
        'ConstProgs_EndBal',
        'TtlPlt_PropEquip_EndBal',
        'AccumDep_EndBal',
        'IntAsst_NetAccumAmo_EndBal',
        'OthCapAsst_EndBalNwAlg',
        'TutFees_AftrDedDiscs_Allows',
        'FedOptGrnt_Contrc',
        'StOptGrnt_Contrc',
        'Lcl_PrvOptGrnt_Contrc',
        'LclOptGrnt_Contrc',
        'PrvOptGrnt_Contrc',
        'IndOps',
        'OtherSrc_Opt',
        'TtlOptRev',
        'LclApp_EduDistTax_SlrSup',
        'FedNonOptGrnt',
        'StNonOptGrnt',
        'LclNonOptGrnt',
        'Gfts_IncContAfflOrg',
        'InvtIncm',
        'OtherNonOptRev',
        'TtlNonOptRev',
        'TtlOpt_NonOptRev',
        'CptApp',
        'CptGrnt_Gfts',
        'AddtnPermEndws',
        'OtherRev_Addtn',
        'TtlOtherRev_Addtn',
        'TtlRev_OtherAddtn',
        'Inst_CrtYrTtl',
        'Inst_SalWages',
        'Inst_EmpFringeBenft',
        'Inst_Ops_MaintOfPlant',
        'Inst_Dep',
        'Inst_Interest',
        'Inst_AllOther',
        'Res_CrtYrTtl',
        'Res_SalWages',
        'Res_EmpFringeBft',
        'Res_Ops_MaintOfPlant',
        'Res_Dep',
        'Res_Interest',
        'Res_AllOther',
        'PubServ_CrtYrTtl',
        'PubServ_SalWages',
        'PubServ_EmpFringeBft',
        'PubServ_Ops_MaintOfPlant',
        'PubServ_Dep',
        'PubServ_Interest',
        'PubServ_AllOther',
        'AcdSup_CrtYrTtl',
        'AcadSup_SalWages',
        'AcadSup_EmpFringeBft',
        'AcadSup_Ops_MaintOfPlant',
        'AcadSup_Dep',
        'AcadSup_Int',
        'AcadSup_AllOther',
        'StdSer_CrtYrTtl',
        'StdServ_SalWages',
        'StdServ_EmpFringeBft',
        'StdServ_Ops_MaintOfPlant',
        'StdServ_Dep',
        'StdServ_Int',
        'StdServ_AllOther',
        'InstSup_CrtYrTtl',
        'InsSup_SalWages',
        'InstSup_EmpFringeBft',
        'InstSup_Ops_MaintOfPlant',
        'InstSup_Dep',
        'InstSup_Int',
        'InstSup_AllOther',
        'OpMaintOfPlant_CrtYrTtl',
        'OpMaintOfPlant_SalWages',
        'OpMaintOfPlant_EmpFringeBft',
        'OpMaintOfPlant',
        'OpMaintOfPlant_Dep',
        'OpMaintOfPlant_Int',
        'OpMaintOfPlant_AllOther',
        'Sch_felshpsExp_CrtYrTtl',
        'Sch_felshpsExp_AllOther',
        'AuxEtr_CrtYrTtl',
        'AuxEtr_SalWages',
        'AuxErt_EmpFringeBft',
        'AuxEtr_Ops_MaintOfPlant',
        'AuxEtr_Dep',
        'AuxEtr_Int',
        'AuxEtr_AllOther',
        'HspSer_CrtYrTtl',
        'HspSer_SalWages',
        'HspSer_EmpFringeBft',
        'HspSer_Ops_MaintOfPlant',
        'HspSer_Dep',
        'HspSer_Int',
        'HspSer_AllOther',
        'IndOps_CrtYrTtl',
        'IndOps_SalWages',
        'IndOps_EmpFringeBft',
        'IndOps_Ops_MaintOfPlant',
        'IndOps_Dep',
        'IndOps_Int',
        'IndOps_AllOther',
        'OtherExpDed_CrtYrTtl',
        'OtherExpDed_SalWages',
        'OtherExpDed_EmpFringeBft',
        'OtherExpDed_Ops_MaintOfPlant',
        'OtherExpDed_Dep',
        'OtherExpDed_Int',
        'OtherExpDed_AllOther',
        'TtlExpDed_CrtYrTtl',
        'TtlExpDed_SalWages',
        'TtlExpDed_EmpFringeBft',
        'TtlExpDed_Ops_MaintOfPlant',
        'TtlExpDed_Dep',
        'TtlExpDed_Int',
        'TtlExpDed_AllOther',
        'TtlRev_OtherAdn',
        'TtlExp_OtherDed',
        'CngNet_PstdrgYr',
        'NetPostnBegnOfYr',
        'AdjBegnNetPostn',
        'NetPostnEndYr',
        'PellGrntFederal',
        'GrntStateGovt',
        'GrntLclGovt',
        'InstGrntFrmResRrs',
        'InstGrntFrmUnResRrs',
        'TtlGrSch_felshp',
        'Dis_AlsApplTtn_fees',
        'Dis_AlwAplSls_SerAuxEtr',
        'TtlDis_Alw',
        'NetSch_felshpExp',
    ];
    protected $primaryKey = 'Public_ID';
    public static function getTableName() {
        return (new static)->getTable();
    }

    public function school() {
        return $this->belongsTo('App\School');
    }

}