<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateFinancesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('finances', function (Blueprint $table) {

            $table->increments('Finance_ID');
            $table->integer('School_ID')->unsigned();
            $table->integer('year')->nullable();
            $table->char('Sector_Flag(Pub, Private_NP, Private_P)',25)->nullable();
            $table->integer('TtlNetAssets')->nullable();
            //$table->integer('OthrfederlGrnt')->nullable()->nullable();
            $table->integer('OwnEndowAsst')->nullable();
            $table->integer('ValEndowAsstBegnFisclYr')->nullable();
            $table->integer('ValEndowAsstEndFisclYr')->nullable();
            $table->integer('TtlAsst')->nullable();
            $table->integer('TtlLiabilts')->nullable();
            $table->integer('ConstProg')->nullable();
            $table->integer('OthrPlantPropEquip')->nullable();
            $table->integer('TtlPlantPropEquip')->nullable();
            $table->integer('AccuDepre')->nullable();
            $table->integer('PropPlantEquip_netAcumltdDpr')->nullable();
            $table->integer('IntAsstNetAcmltdAmor')->nullable();
            $table->integer('TtlRevInvReturn')->nullable();
            $table->integer('TtlExpns')->nullable();
            $table->integer('PellGrnt')->nullable();
            //$table->integer('OthrfederlGrnt')->nullable()->nullable();
            $table->integer('StateGrnt')->nullable();
            $table->integer('TtlStudGrant')->nullable();
            $table->integer('AllwncApplTut_fees')->nullable();
            $table->integer('Allwnc AplAux_EntRev')->nullable();
            $table->integer('InstrcTtlAmt')->nullable();
            $table->integer('InstrcSal_wages')->nullable();
            $table->integer('InstrcBenefits')->nullable();
            $table->integer('InstrcOprMaintPlant')->nullable();
            $table->integer('InstrcDep')->nullable();
            $table->integer('InstrcInterest')->nullable();
            $table->integer('InstrcAllOthr')->nullable();
            $table->integer('RsrchTtlAmt')->nullable();
            $table->integer('RsrchSal_wages')->nullable();
            $table->integer('RsrchBenefits')->nullable();
            $table->integer('RsrchOprMaintPlant')->nullable();
            $table->integer('RsrchDep')->nullable();
            $table->integer('RsrchInterest')->nullable();
            $table->integer('RsrchAllOthr')->nullable();
            $table->integer('PubSrvcTtlAmnt')->nullable();
            $table->integer('PubSrvcSal_wages')->nullable();
            $table->integer('PubSrvcBenefits')->nullable();
            $table->integer('PubSrvcOprMaintPlant')->nullable();
            $table->integer('PubSrvcDep')->nullable();
            $table->integer('PubSrvcInt')->nullable();
            $table->integer('PubSrvcAllOthr')->nullable();
            $table->integer('AcadSuprtTtlAmnt')->nullable();
            $table->integer('AcadSuprtSal_wage')->nullable();
            $table->integer('AcadSuprtBenefits')->nullable();
            $table->integer('AcadSuprtOprMaintPlant')->nullable();
            $table->integer('AcadSuprtDep')->nullable();
            $table->integer('AcadSuprtInterest')->nullable();
            $table->integer('AcadSuprtAllOthr')->nullable();
            $table->integer('StudSrvcTtlAmt')->nullable();
            $table->integer('StudSrvcSal_Wages')->nullable();
            $table->integer('StudSrvcBenefits')->nullable();
            $table->integer('StudSrvcOprMaintPlant')->nullable();
            $table->integer('StudSrvcDep')->nullable();
            $table->integer('StudSrvcInterest')->nullable();
            $table->integer('StudSrvcAllOthr')->nullable();
            $table->integer('InstSprtTtlAmt')->nullable();
            $table->integer('InstSprtSal_wages')->nullable();
            $table->integer('InstSprtBenefits')->nullable();
            $table->integer('InstSprtOprMaintPlant')->nullable();
            $table->integer('InstSprtDepreciation')->nullable();
            $table->integer('InstSprtInterest')->nullable();
            $table->integer('InstSprtAllOthr')->nullable();
            $table->integer('AuxEntrpTtlAmt')->nullable();
            $table->integer('AuxEntrpSal_wages')->nullable();
            $table->integer('AuxEntrpBenefits')->nullable();
            $table->integer('AuxEntrpOprMaintPlant')->nullable();
            $table->integer('AuxEntrpDep')->nullable();
            $table->integer('AuxEntrpInterest')->nullable();
            $table->integer('AuxEntrpAllOthr')->nullable();
            $table->integer('Net_grantAid_StudsTtlAmt')->nullable();
            $table->integer('Net_grantAid_StudsAllOthr')->nullable();
            $table->integer('HsptlSrvcsTtlAmnt')->nullable();
            $table->integer('HsptlSrvcsSalWage')->nullable();
            $table->integer('HsptlSrvcsBenefits')->nullable();
            $table->integer('HsptlSrvcsOprMaintPlant')->nullable();
            $table->integer('HsptlSrvcsDep')->nullable();
            $table->integer('HsptlSrvcsInt')->nullable();
            $table->integer('HsptlSrvcsAllOthr')->nullable();
            $table->integer('OprMaintPlantTtlAmt')->nullable();
            $table->integer('OprMaintPlantSal_wages')->nullable();
            $table->integer('OprMaintPlantBenefits')->nullable();
            $table->integer('OprMaintPlantOprMaintPlant')->nullable();
            $table->integer('OprMaintPlantDep')->nullable();
            $table->integer('OprMaintPlantInt')->nullable();
            $table->integer('OprMaintPlantAllOthr')->nullable();
            $table->integer('OthrExpnsTtlAmnt')->nullable();
            $table->integer('OthrExpnsSal_wages')->nullable();
            $table->integer('OthrExpnsBenefits')->nullable();
            $table->integer('OthrExpnsOprMaintPlant')->nullable();
            $table->integer('OthrExpnsDprctn')->nullable();
            $table->integer('OthrExpnsIntrst')->nullable();
            $table->integer('OthrExpnsAlOthr')->nullable();
            $table->integer('TtlExpnsTtlAmnt')->nullable();
            $table->integer('TtlExpnsSlrWages')->nullable();
            $table->integer('TtlExpnsBnfits')->nullable();
            $table->integer('TtlExpnsDprctn')->nullable();
            $table->integer('TtlExpnsIntrst')->nullable();
            $table->integer('TtlExpnsAllOthr')->nullable();
            //$table->integer('TtlAsst')->nullable()->nullable();
            //$table->integer('TtlLiabilts')->nullable()->nullable();
            //$table->integer('TtlAsst')->nullable()->nullable();
            //$table->integer('TtlLiabilts')->nullable()->nullable();
            $table->integer('OthrfederlGrnt')->nullable();
            $table->integer('FedApp')->nullable();
            $table->integer('StApp')->nullable();
            $table->integer('Sale_SrvcsEductnActv')->nullable();
            $table->integer('Sales_SrvcsAuxEntrp')->nullable();
            /*$table->char('X_TtlNetAssets',5)->nullable();
            $table->char('X_OthrfederlGrnt',5)->nullable();
            $table->char('X_OwnEndowAsst',5)->nullable();
            $table->char('X_ValEndowAsstBegnFisclYr',5)->nullable();
            $table->char('X_ValEndowAsstEndFisclYr',5)->nullable();
            $table->char('X_TtlAsst',5)->nullable();
            $table->char('X_TtlLiabilts',5)->nullable();
            $table->char('X_ConstProg',5)->nullable();
            $table->char('X_OthrPlantPropEquip',5)->nullable();
            $table->char('X_TtlPlantPropEquip',5)->nullable();
            $table->char('X_AccuDepre',5)->nullable();
            $table->char('X_PropPlantEquip_netAcumltdDp',5)->nullable();
            $table->char('X_IntAsstNetAcmltdAmor',5)->nullable();
            $table->char('X_TtlRevInvReturn',5)->nullable();
            $table->char('X_TtlExpns',5)->nullable();
            $table->char('X_PellGrnt',5)->nullable();
            //$table->char('X_OthrfederlGrnt')->nullable()->nullable();
            $table->char('X_StateGrnt',5)->nullable();
            $table->char('X_TtlStudGrant',5)->nullable();
            $table->char('X_AllwncApplTut_fees',5)->nullable();
            $table->char('X_Allwnc AplAux_EntRev',5)->nullable();
            $table->char('X_InstrcTtlAmt',5)->nullable();
            $table->char('X_InstrcSal_wages',5)->nullable();
            $table->char('X_InstrcBenefits',5)->nullable();
            $table->char('X_InstrcOprMaintPlant',5)->nullable();
            $table->char('X_InstrcDep',5)->nullable();
            $table->char('X_InstrcInterest',5)->nullable();
            $table->char('X_InstrcAllOthr',5)->nullable();
            $table->char('X_RsrchTtlAmt',5)->nullable();
            $table->char('X_RsrchSal_wages',5)->nullable();
            $table->char('X_RsrchBenefits',5)->nullable();
            $table->char('X_RsrchOprMaintPlant',5)->nullable();
            $table->char('X_RsrchDep',5)->nullable();
            $table->char('X_RsrchInterest',5)->nullable();
            $table->char('X_RsrchAllOthr',5)->nullable();
            $table->char('X_PubSrvcTtlAmnt',5)->nullable();
            $table->char('X_PubSrvcSal_wages',5)->nullable();
            $table->char('X_PubSrvcBenefits',5)->nullable();
            $table->char('X_PubSrvcOprMaintPlant',5)->nullable();
            $table->char('X_PubSrvcDep',5)->nullable();
            $table->char('X_PubSrvcInt',5)->nullable();
            $table->char('X_PubSrvcAllOthr',5)->nullable();
            $table->char('X_AcadSuprtTtlAmnt',5)->nullable();
            $table->char('X_AcadSuprtSal_Wage',5)->nullable();
            $table->char('X_AcadSuprtBenefits',5)->nullable();
            $table->char('X_AcadSuprtOprMaintPlant',5)->nullable();
            $table->char('X_AcadSuprtDep',5)->nullable();
            $table->char('X_AcadSuprtInterest',5)->nullable();
            $table->char('X_AcadSuprtAllOthr',5)->nullable();
            $table->char('X_StudSrvcTtlAmt',5)->nullable();
            $table->char('X_StudSrvcSal_Wages',5)->nullable();
            $table->char('X_StudSrvcBenefits',5)->nullable();
            $table->char('X_StudSrvcOprMaintPlant',5)->nullable();
            $table->char('X_StudSrvcDep',5)->nullable();
            $table->char('X_StudSrvcInt',5)->nullable();
            $table->char('X_StudSrvcAllOthr',5)->nullable();
            $table->char('X_InstSprtTtlAmt',5)->nullable();
            $table->char('X_InstSprtSal_wages',5)->nullable();
            $table->char('X_InstSprtBenefits',5)->nullable();
            $table->char('X_InstSprtOprMaintPlant',5)->nullable();
            $table->char('X_InstSprtDepreciation',5)->nullable();
            $table->char('X_InstSprtInterest',5)->nullable();
            $table->char('X_InstSprtAllOthr',5)->nullable();
            $table->char('X_AuxEntrpTtlAmt',5)->nullable();
            $table->char('X_AuxEntrpSal_wages',5)->nullable();
            $table->char('X_AuxEntrpBenefits',5)->nullable();
            $table->char('X_AuxEntrpOprMaintPlant',5)->nullable();
            $table->char('X_AuxEntrpDep',5)->nullable();
            $table->char('X_AuxEntrpInterest',5)->nullable();
            $table->char('X_AuxEntrpAllOthr',5)->nullable();
            $table->char('X_Net_grant_aid_StudsTtlAmt',5)->nullable();
            $table->char('X_Net_grant_aid_StudsAllOthr',5)->nullable();
            $table->char('X_HsptlSrvcsTtlAmnt',5)->nullable();
            $table->char('X_HsptlSrvcsSalWage',5)->nullable();
            $table->char('X_HsptlSrvcsBenefits',5)->nullable();
            $table->char('X_HsptlSrvcsOprMaintPlant',5)->nullable();
            $table->char('X_HsptlSrvcsDep',5)->nullable();
            $table->char('X_HsptlSrvcsInt',5)->nullable();
            $table->char('X_HsptlSrvcsAllOthr',5)->nullable();
            $table->char('X_OprMaintPlantTtlAmt',5)->nullable();
            $table->char('X_OprMaintPlantSal_wages',5)->nullable();
            $table->char('X_OprMaintPlantBenefits',5)->nullable();
            $table->char('X_OprMaintPlantOprMaintPlant',5)->nullable();
            $table->char('X_OprMaintPlantDep',5)->nullable();
            $table->char('X_OprMaintPlantInt',5)->nullable();
            $table->char('X_OprMaintPlantAllOthr',5)->nullable();
            $table->char('X_OthrExpnsTtlAmnt',5)->nullable();
            $table->char('X_OthrExpnsSal_wages',5)->nullable();
            $table->char('X_OthrExpnsBenefits',5)->nullable();
            $table->char('X_OthrExpnsOprMaintPlant',5)->nullable();
            $table->char('X_OthrExpnsDprctn',5)->nullable();
            $table->char('X_OthrExpnsIntrst',5)->nullable();
            $table->char('X_OthrExpnsAlOthr',5)->nullable();
            $table->char('X_TtlExpnsTtlAmnt',5)->nullable();
            $table->char('X_TtlExpnsSlrWages',5)->nullable();
            $table->char('X_TtlExpnsBnfits',5)->nullable();
            $table->char('X_TtlExpnsDprctn',5)->nullable();
            $table->char('X_TtlExpnsIntrst',5)->nullable();
            $table->char('X_TtlExpnsAllOthr',5)->nullable();
            //$table->char('X_TtlAsst')->nullable()->nullable();
            //$table->char('X_TtlLiabilts')->nullable()->nullable();
            //$table->char('X_TtlAsst')->nullable()->nullable();
            //$table->char('X_TtlLiabilts')->nullable()->nullable();
            //$table->char('X_OthrfederlGrnt')->nullable()->nullable();
            $table->char('X_FedApp',5)->nullable();
            $table->char('X_StApp',5)->nullable();
            $table->char('X_Sale_SrvcsEductnActv',5)->nullable();
            $table->char('X_Sales_SrvcsAuxEntrp',5)->nullable();*/
            $table->string('created_by')->default('System');
            $table->string('updated_by')->default('System');
            $table->timestamps();
            $table->softDeletes();
            $table->foreign('School_ID')->references('School_ID')->on('schools')->onUpdate('cascade')->onDelete('cascade');

        });

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('finances');
    }
}
